In [52]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("zepto_v2.csv")


df.head()

,Category,name,mrp,discountPercent,availableQuantity,discountedSellingPrice,weightInGms,outOfStock,quantity
0,Fruits & Vegetables,Onion,2500,16,3,2100,1000,False,1
1,Fruits & Vegetables,Tomato Hybrid,4200,16,3,3500,1000,False,1
2,Fruits & Vegetables,Tender Coconut,5100,15,3,4300,58,False,1
3,Fruits & Vegetables,Coriander Leaves,2000,15,3,1700,100,False,100
4,Fruits & Vegetables,Ladies Finger,1400,14,3,1200,250,False,250

In [53]:
# Shape of the dataset
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

# Column names
print(df.columns.tolist())

# Dataset information
df.info()

Rows: 3732
Columns: 9
['Category', 'name', 'mrp', 'discountPercent', 'availableQuantity', 'discountedSellingPrice', 'weightInGms', 'outOfStock', 'quantity']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3732 entries, 0 to 3731
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Category                3732 non-null   object
 1   name                    3732 non-null   object
 2   mrp                     3732 non-null   int64
 3   discountPercent         3732 non-null   int64
 4   availableQuantity       3732 non-null   int64
 5   discountedSellingPrice  3732 non-null   int64
 6   weightInGms             3732 non-null   int64
 7   outOfStock              3732 non-null   bool
 8   quantity                3732 non-null   int64
dtypes: bool(1), int64(6), object(2)
memory usage: 237.0+ KB

In [54]:
missing = df.isnull().sum()
print(missing)

Category                  0
name                      0
mrp                       0
discountPercent           0
availableQuantity         0
discountedSellingPrice    0
weightInGms               0
outOfStock                0
quantity                  0
dtype: int64

In [55]:
duplicate= df.duplicated().sum()
print(duplicate)

2

In [56]:
df[df.duplicated()]

,Category,name,mrp,discountPercent,availableQuantity,discountedSellingPrice,weightInGms,outOfStock,quantity
2946,Personal Care,Listerine Cool Mint Mouthwash - Mild Taste,15000,10,6,13500,250,False,250
3290,Paan Corner,Listerine Cool Mint Mouthwash - Mild Taste,15000,10,6,13500,250,False,250

In [57]:
df=df.drop_duplicates()
print(df)

                 Category                                               name  \
0     Fruits & Vegetables                                              Onion
1     Fruits & Vegetables                                      Tomato Hybrid
2     Fruits & Vegetables                                     Tender Coconut
3     Fruits & Vegetables                                   Coriander Leaves
4     Fruits & Vegetables                                     Ladies Finger
...                   ...                                                ...
3727     Health & Hygiene  Stayfree Secure Dry Cover Extra Large Sanitary...
3728     Health & Hygiene  Dabur Honitus Herbal Cough Remedy Ayurvedic Syrup
3729     Health & Hygiene       Whisper Bindazzz Night Sanitary Pads XL Plus
3730     Health & Hygiene                             Fine Life Cotton Balls
3731     Health & Hygiene                           Dettol Antiseptic Liquid

        mrp  discountPercent  availableQuantity  discountedSellingPrice  \
0      2500               16                  3                    2100
1      4200               16                  3                    3500
2      5100               15                  3                    4300
3      2000               15                  3                    1700
4      1400               14                  3                    1200
...     ...              ...                ...                     ...
3727   4200                2                  0                    4100
3728  10500               15                  0                    8900
3729  18500                0                  0                   18500
3730   6000                0                  0                    6000
3731   3000                0                  0                    3000

      weightInGms  outOfStock  quantity
0            1000       False         1
1            1000       False         1
2              58       False         1
3             100       False       100
4             250       False       250
...           ...         ...       ...
3727          406        True         7
3728          100        True       100
3729          870        True        15
3730           50        True        50
3731           60        True        60

[3730 rows x 9 columns]

In [58]:
df.shape

(3730, 9)

In [59]:
df[df.duplicated()]

Empty DataFrame
Columns: [Category, name, mrp, discountPercent, availableQuantity, discountedSellingPrice, weightInGms, outOfStock, quantity]
Index: []

In [60]:
df.dtypes

Category                  object
name                      object
mrp                        int64
discountPercent            int64
availableQuantity          int64
discountedSellingPrice     int64
weightInGms                int64
outOfStock                  bool
quantity                   int64
dtype: object

As we can see the prices are in paisa not in rupees we'll covert this in rupees

In [61]:
# Look at a few price values
df[['mrp', 'discountedSellingPrice']].head(10)

    mrp  discountedSellingPrice
0  2500                    2100
1  4200                    3500
2  5100                    4300
3  2000                    1700
4  1400                    1200
5  3500                    2900
6  7500                    6300
7  5800                    4900
8  2300                    1900
9  1900                    1600

In [62]:
# Convert paise to rupees
df['mrp_rupees'] = df['mrp'] / 100
df['selling_price_rupees'] = df['discountedSellingPrice'] / 100

In [63]:
df[['mrp', 'mrp_rupees',
    'discountedSellingPrice', 'selling_price_rupees']].head()

    mrp  mrp_rupees  discountedSellingPrice  selling_price_rupees
0  2500        25.0                    2100                  21.0
1  4200        42.0                    3500                  35.0
2  5100        51.0                    4300                  43.0
3  2000        20.0                    1700                  17.0
4  1400        14.0                    1200                  12.0

In [64]:
df.shape

(3730, 11)

In [65]:
df.drop(columns=["mrp","discountedSellingPrice"] ,inplace=True)

In [66]:
df.shape

(3730, 9)

In [67]:
df[df["selling_price_rupees"] > df["mrp_rupees"]]

Empty DataFrame
Columns: [Category, name, discountPercent, availableQuantity, weightInGms, outOfStock, quantity, mrp_rupees, selling_price_rupees]
Index: []

In [68]:
df[
    (df["discountPercent"] < 0) |
    (df["discountPercent"] > 100)
]

Empty DataFrame
Columns: [Category, name, discountPercent, availableQuantity, weightInGms, outOfStock, quantity, mrp_rupees, selling_price_rupees]
Index: []

In [69]:
df[df["weightInGms"] <= 0]

,Category,name,discountPercent,availableQuantity,weightInGms,outOfStock,quantity,mrp_rupees,selling_price_rupees
2840,Personal Care,Maybelline New York Colossal Kajal Black,0,2,0,False,0,149.0,149.0
2929,Personal Care,Maybelline New York Colossal Kajal Super Black,8,3,0,False,0,300.0,275.0
3184,Paan Corner,Maybelline New York Colossal Kajal Black,0,2,0,False,0,149.0,149.0
3273,Paan Corner,Maybelline New York Colossal Kajal Super Black,8,3,0,False,0,300.0,275.0

In [70]:
df[df["availableQuantity"] < 0]

Empty DataFrame
Columns: [Category, name, discountPercent, availableQuantity, weightInGms, outOfStock, quantity, mrp_rupees, selling_price_rupees]
Index: []

In [71]:
df[df["mrp_rupees"] <= 0]

,Category,name,discountPercent,availableQuantity,weightInGms,outOfStock,quantity,mrp_rupees,selling_price_rupees
3606,Home & Cleaning,Cherry Blossom Liquid Shoe Polish Neutral,0,1,75,False,75,0.0,0.0

In [73]:
df.shape

(3729, 9)

In [72]:
df.drop(df[df['mrp_rupees'] <= 0].index,inplace=True)

In [74]:
df.drop(df[df['weightInGms'] <= 0].index,inplace=True)

In [75]:
df.shape

(3725, 9)

In [76]:
invalid_quantity = df[df["availableQuantity"] < 0]

print(f"Negative Quantity Records: {len(invalid_quantity)}")
invalid_quantity

Negative Quantity Records: 0

Empty DataFrame
Columns: [Category, name, discountPercent, availableQuantity, weightInGms, outOfStock, quantity, mrp_rupees, selling_price_rupees]
Index: []

In [77]:
df.groupby("outOfStock")["availableQuantity"].describe()

             count      mean       std  min  25%  50%  75%  max
outOfStock
False       3272.0  4.565098  1.730562  1.0  3.0  5.0  6.0  6.0
True         453.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0

In [78]:
df.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731],
      dtype='int64', length=3725)

In [79]:
df.head()

,Category,name,discountPercent,availableQuantity,weightInGms,outOfStock,quantity,mrp_rupees,selling_price_rupees
0,Fruits & Vegetables,Onion,16,3,1000,False,1,25.0,21.0
1,Fruits & Vegetables,Tomato Hybrid,16,3,1000,False,1,42.0,35.0
2,Fruits & Vegetables,Tender Coconut,15,3,58,False,1,51.0,43.0
3,Fruits & Vegetables,Coriander Leaves,15,3,100,False,100,20.0,17.0
4,Fruits & Vegetables,Ladies Finger,14,3,250,False,250,14.0,12.0

In [80]:
df.shape

(3725, 9)

In [81]:

df.to_csv(
    "zepto_cleaned.csv",
    index=False,
    encoding="utf-8"

)

In [51]:
df = pd.read_csv("zepto_cleaned.csv")
df.head()

,sku,Category,name,discountPercent,availableQuantity,weightInGms,outOfStock,quantity,mrp_rupees,selling_price_rupees
0,1,Fruits & Vegetables,Onion,16,3,1000,False,1,25.0,21.0
1,2,Fruits & Vegetables,Tomato Hybrid,16,3,1000,False,1,42.0,35.0
2,3,Fruits & Vegetables,Tender Coconut,15,3,58,False,1,51.0,43.0
3,4,Fruits & Vegetables,Coriander Leaves,15,3,100,False,100,20.0,17.0
4,5,Fruits & Vegetables,Ladies Finger,14,3,250,False,250,14.0,12.0

In [48]:
df.shape

(3725, 10)